#!/bin/sh
rm /var/tmp/feh-dev_pkg-plist 2>/dev/null
rm /var/tmp/feh-dev_pkg-plist-fixed 2>/dev/null
cp ../pkg-plist /var/tmp/feh-dev_pkg-plist

echo "adding conditional list tags"

cat /var/tmp/feh-dev_pkg-plist | \
sed \
-e 's#%\%PORTDOCS\%\%\%\%DOCSDIR\%\%/examples#\%\%EXAMPLES\%\%\%\%PORTDOCS\%\%\%\%DOCSDIR\%\%/examples#' \
> /var/tmp/feh-dev_pkg-plist-fixed
cp /var/tmp/feh-dev_pkg-plist-fixed ../pkg-plist
